### ISSUE TITLE
Logging Issue in Discord Voice Channels

### ISSUE THREAD

**Issue by EEnigma-Hub** [HDR/OpenLoggerBot#1]
When I use the mute and unmute buttons while in a voice channel on Discord, a log message indicating that I've joined the voice is sent. However, I'm already in a voice channel, and when I mute and unmute my voice, multiple log messages are sent to the log channels. Can you please help me solve this issue?

https://github.com/HDR/OpenLoggerBot/assets/49907273/eba985f4-83f2-4102-b004-574ec852e2b8

**Comment by HDR** [comment]
Thanks for pointing this out, should be fixed in 4ef3c8e
